<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.erp</groupId>
        <artifactId>erp-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>erp-module-sales</artifactId>
    <packaging>pom</packaging>
    <description>销售模块</description>

    <modules>
        <module>erp-module-sales-api</module>
        <module>erp-module-sales-biz</module>
    </modules>
</project>
